version: "3.1"

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - app-network

  www:
    build: .
    ports:
      - "0.0.0.0:3000:3000" # Mapea el puerto 3000 del contenedor al 3000 de la máquina
    volumes:
      - ./:/usr/src/app # Monta el directorio actual al directorio de trabajo del backend
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://10.140.15.36:8081 # Ajusta según tu IP
      - PORT=3000 # Asegura que el backend use el puerto 3000
    depends_on:
      - db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    networks:
      - app-network

volumes:
  persistent:

networks:
  app-network:
    driver: bridge