POST http://localhost:3001/api/admin/login
Content-Type: application/json

{
  "nif": "11122233A",
  "password": "11122233A"
}

###logout
POST http://localhost:3001/api/admin/logout
Content-Type: application/json

{
  "nif": "11122233A"
}

### get admin by id
GET http://localhost:3001/api/admin/1
