@token = your_actual_token_here

POST http://localhost:3001/api/gestor/login
Content-Type: application/json

{
  "nif": "11122233A",
  "password": "11122233A"
}

###logout
POST http://localhost:3001/api/gestor/logout
Content-Type: application/json

{
  "nif": "11122233A"
}

### get gestor by id
GET http://localhost:3001/api/gestor/1

### 
GET http://localhost:3001/api/gestor/solicitudes/2

### Aceptar solicitud ID=6
PATCH http://localhost:3001/api/gestor/solicitudes/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "estado": "aceptada"
}

###

### Rechazar solicitud ID=6
PATCH http://localhost:3001/api/gestor/solicitudes/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "estado": "rechazada"
}







